name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build the book
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install Asciidoctor gem
      run: gem install asciidoctor
    - name: Recreate gh-pages
      run: |
        git branch -D gh-pages 1>/dev/null 2>/dev/null || true
        git checkout -q --orphan gh-pages 1>/dev/null
        mv ./docs/* .
        rm -rf .github
    - name: Build documents
      run: |
        asciidoctor --version
        find . -name "*.adoc" | xargs asciidoctor
    - name: Commit and Push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Asciidoc build"
        git push -f --set-upstream origin gh-pages
