name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build the book
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
    - name: Install Asciidoctor gem
      run: gem install asciidoctor
    - name: Build documents
      run: |
        asciidoctor --version
        asciidoctor docs/*.adoc
