name: CI
on: [push, pull_request]

jobs:
  build:
    name: Build the book
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install Asciidoctor gem
      run: gem install asciidoctor
    - name: Build documents
      run: |
        asciidoctor --version
        asciidoctor docs/*.adoc
    - name: Commit and Push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add ./docs
        git commit -m "Asciidoc build"
        git push
